# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
markdown:            kramdown
title:               'HomePage'
tagline:             'Vincent Richefeu'
description:         "Mes recherches portent sur la physique et la mécanique des milieux granulaires en mettant l'accent sur les petites échelles (<i>i.e.</i> celles des contacts, des particules, et/ou des pores)"
url:                 "https://richefeu.github.io/homepage-vrichefeu"
baseurl:             "/homepage-vrichefeu"
paginate:            5

# About/contact
author:
  name:              Vincent Richefeu
  url:               http://www.3sr-grenoble.fr
  email:             vincent.richefeu@3sr-grenoble.fr

# Custom vars
version:             1.0.0
