# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
markdown:            kramdown
title:               'HomePage'
tagline:             'Vincent Richefeu'
description:         "Physique des milieux granulaires des éléments discrets à l'ouvrage"
url:                 "https://richefeu.github.io/homepage-vrichefeu"
baseurl:             "/homepage-vrichefeu"
#paginate:            5

# About/contact
author:
  name:              Vincent Richefeu
  url:               http://www.3sr-grenoble.fr
  email:             vincent.richefeu@univ-grenoble-alpes.fr

# Custom vars
version:             1.0.0
